# Travis doesn't package ghc-8.0

sudo: required
services:
  - docker

# specifying language here breaks Travis

script:
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    debian:sid
    /bin/bash -ex .travis.sh
